### ISSUE TITLE
Adding Time-Lost Artifact to the Teleport/Hearth Section

### ISSUE THREAD

**Issue by KarlmitC** [Kresx/DynamicCamBFA#1]
Hi there,

I added it for myself already but I just wanted to suggest adding the Time-Lost Artifact to the Teleport/Hearth Section. The triggering spell is called "Call by the Mists" and has the id 145430.

**Comment by Kresx** [comment]
Thanks for reporting this as an issue :+1: I've gone ahead and added it!
